# Simplified values file
replicaCount: 1

image:
  repository: null  # Will be set by deploy.sh
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer 
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Simple autoscaling config
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
